Bugfix
	* Added support for bugfix
	* Fixed errors on init

diff --git a/git-flow-bugfix b/git-flow-bugfix
--- a/git-flow-bugfix
+++ b/git-flow-bugfix
@@ -40,7 +40,7 @@ init() {
   require_git_repo
   require_gitflow_initialized
   gitflow_load_settings
-  PREFIX=$(git config --get gitflow.prefix.sprint)
+  load_prefix_with_sprint
 }
 
 usage() {
@@ -53,11 +53,97 @@ cmd_default() {
 }
 
 cmd_list() {
+  parse_args "$@"
+
+  local feature_branches
+  local current_branch
+  local short_names
+  feature_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+  if [ -z "$feature_branches" ]; then
+    warn "No bugfix branches exist."
+    warn ""
+    warn "You can start a new bugfix branch:"
+    warn ""
+    warn "    git flow bugfix start <name> [<base>]"
+    warn ""
+    exit 0
+  fi
+  current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
+  short_names=$(echo "$feature_branches" | sed "s ^$PREFIX  g")
+
+  # determine column width first
+  local width=0
+  local branch
+  for branch in $short_names; do
+    local len=${#branch}
+    width=$(max $width $len)
+  done
+  width=$(($width+3))
+
+  local branch
+  for branch in $short_names; do
+    local fullname=$PREFIX$branch
+    local base=$(git merge-base "$fullname" "$DEVELOP_BRANCH")
+    local develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
+    local branch_sha=$(git rev-parse "$fullname")
+    if [ "$fullname" = "$current_branch" ]; then
+      printf "* "
+    else
+      printf "  "
+    fi
+    if flag verbose; then
+      printf "%-${width}s" "$branch"
+      if [ "$branch_sha" = "$develop_sha" ]; then
+        printf "(no commits yet)"
+      elif [ "$base" = "$branch_sha" ]; then
+        printf "(is behind develop, may ff)"
+      elif [ "$base" = "$develop_sha" ]; then
+        printf "(based on latest develop)"
+      else
+        printf "(may be rebased)"
+      fi
+    else
+      printf "%s" "$branch"
+    fi
+    echo
+  done
 
 }
 
 cmd_start() {
-  parse_args "%@"
+  DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
+  parse_args "$@"
+  BASE=${2:-$DEVELOP_BRANCH}
+  require_name_arg
+
+  # sanity checks
+  require_branch_absent "$BRANCH"
+
+  # update the local repo with remote changes, if asked
+  if flag fetch; then
+    git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+  fi
+
+  # if the origin branch counterpart exists, assert that the local branch
+  # isn't behind it (to avoid unnecessary rebasing)
+  if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
+    require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+  fi
+
+  # create branch
+  if ! git_do checkout -b "$BRANCH" "$BASE"; then
+    die "Could not create feature branch '$BRANCH'"
+  fi
+
+  echo
+  echo "Summary of actions:"
+  echo "- A new branch '$BRANCH' was created, based on '$BASE'"
+  echo "- You are now on branch '$BRANCH'"
+  echo ""
+  echo "Now, start committing on your feature. When done, use:"
+  echo ""
+  echo "     git flow bugfix finish $NAME"
+  echo
 }
 
 cmd_help() {
@@ -68,8 +154,29 @@ cmd_help() {
 
 # Helper functions
 
+load_prefix_with_sprint() {
+  PREFIX=$(git config --get gitflow.prefix.bugfix)
+  SPRINT=$(git config --get gitflow.sprint.current)
+
+  if [ -n $SPRINT ]; then
+    PREFIX=$SPRINT$PREFIX
+  fi
+}
+
 parse_args() {
   # parse options
   FLAGS "$@" || exit $?
   eval set -- "${FLAGS_ARGV}"
+
+  # read arguments into global variables
+  NAME=$1
+  BRANCH=$PREFIX$NAME
+}
+
+require_name_arg() {
+  if [ "$NAME" = "" ]; then
+    warn "Missing argument <name>"
+    usage
+    exit 1
+  fi
 }
